version: "3.8"

name: P2P_Proj
services:
  node1:
    container_name: node1
    build: .
    ports:
      - "65432"
    networks:
      - network
  node2:
    container_name: node2
    build: .
    ports:
      - "65432"
    networks:
      - network
  node3:
    container_name: node3
    build: .
    ports:
      - "65432"
    networks:
      - network
  node4:
    container_name: node4
    build: .
    ports:
      - "65432"
    networks:
      - network
networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.48.0.0/24"
          gateway: "172.48.0.1"
