version: "3.8"

services:
  server_node:
    container_name: compose_server
    build: .
    ports:
      - "65432:65432"
  client_node:
    container_name: compose_client
    build:
      dockerfile: Dockerfile_client
