version: "3.8"

name: P2P_Network
services:
  server:
    container_name: server1
    build: .
    ports:
      - "65432:65432"
    networks:
      - network
  client:
    container_name: client1
    build:
      dockerfile: Dockerfile_client
    networks:
      - network
networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.48.0.0/24"
          gateway: "172.48.0.1"
